# Generated by Django 4.1.7 on 2023-03-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_past_date_expense_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='expense_date',
        ),
    ]
