# Generated by Django 4.1.7 on 2023-03-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='ticker',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
    ]
