# Generated by Django 4.1.7 on 2023-03-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_currency_name_alter_currency_ticker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['ticker'], 'verbose_name_plural': 'Currencies'},
        ),
    ]
